# Generated by Django 5.1.5 on 2025-01-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_additionalattractionsinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalattractionsinfo",
            name="is_tourist_attractions_active",
            field=models.BooleanField(default=True),
        ),
    ]
